AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Jersey API - my.service::jersey-sample
Outputs:
  JerseySampleApi:
    Description: URL for application
    Export:
      Name: JerseySampleApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
Resources:
  JerseySampleFunction:
    Properties:
      CodeUri: s3://cs6650-hw1/1e9c25e449af3a443595aeac83e0f4e6
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: my.service.StreamLambdaHandler::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
